datasources: 
 datasources.yaml:
   apiVersion: 1
   datasources:
   - name: Prometheus
     type: prometheus
     url: http://prometheus-server.prometheus.svc.cluster.local
     access: proxy
     isDefault: true
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx    
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  hosts: ["a39d223c081044be586feb565045d2df-1072863890.us-east-1.elb.amazonaws.com"]
  path: /grafana/?(.*)
  pathType: Prefix
grafana.ini:
  server:
    root_url: "%(protocol)s://%(domain)s/grafana"