repositories:
 - name: prometheus-community
   url: https://prometheus-community.github.io/helm-charts
 - name: grafana
   url: https://grafana.github.io/helm-charts
 - name: ingress-nginx
   url: https://kubernetes.github.io/ingress-nginx

helmDefaults:
  createNamespace: true

releases:
- name: prometheus
  namespace: prometheus
  chart: prometheus-community/prometheus
  values: 
    - prometheus.yaml
  version: 19.3.3
- name: grafana
  namespace: grafana
  chart: grafana/grafana
  values:
    - grafana.yaml
  version: 6.50.6
- name: ingress-nginx
  namespace: ingress-nginx
  chart: ingress-nginx/ingress-nginx
  values:
    - ingress-nginx.yaml
  version: 4.4.3
- name: hpa-example
  namespace: userapps
  chart: ./charts/hpa-example
  values:
    - hpa-example.yaml
  version: 0.1.0