serverFiles:
  prometheus.yml:
    scrape_configs:
      - job_name: nginx
        static_configs:
          - targets:
            - ingress-nginx-controller-metrics.ingress-nginx.svc.cluster.local:10254